[package]
name = "wibaeowibtnr"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
erupt = "0.16"
gpu-alloc-erupt = "0.1"
gpu-alloc = "0.2"
bytemuck = "1.3"
slotmap = "1.0"
